name: dart_json_mapper
version: 2.2.17
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  analyzer: '>=4.3.0 <6.6.0'
  build: ^2.0.0
  build_config: ^1.1.2
  intl: ^0.20.2
  meta: ^1.16.0
  path: ^1.8.3
  reflectable: ^4.0.12
  collection: ^1.19.1
  pubspec_parse: ^1.5.0
dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.4.0
dependency_overrides:
  analyzer: '>=4.3.0 <6.6.0'